const heroes = [
  { name: 'Abaddon', main_attr: 'agi', attrs: { agi: 17, str: 21, intel: 15 } },
  { name: 'Alchemist', main_attr: 'str', attrs: { agi: 16, str: 21, intel: 15 } },
  { name: 'Ancient Apparition', main_attr: 'intel', attrs: { agi: 22, str: 18, intel: 25 } },
  { name: 'Anti-Mage', main_attr: 'agi', attrs: { agi: 20, str: 22, intel: 23 } },
  { name: 'Arc Warden', main_attr: 'agi', attrs: { agi: 15, str: 23, intel: 23 } },
  { name: 'Axe', main_attr: 'str', attrs: { agi: 23, str: 20, intel: 20 } },
  { name: 'Bane', main_attr: 'intel', attrs: { agi: 16, str: 15, intel: 25 } },
  { name: 'Batrider', main_attr: 'intel', attrs: { agi: 25, str: 23, intel: 15 } },
  { name: 'Beastmaster', main_attr: 'str', attrs: { agi: 15, str: 24, intel: 17 } },
  { name: 'Bloodseeker', main_attr: 'agi', attrs: { agi: 22, str: 25, intel: 17 } },
  { name: 'Bounty Hunter', main_attr: 'agi', attrs: { agi: 22, str: 24, intel: 16 } },
  { name: 'Brewmaster', main_attr: 'str', attrs: { agi: 16, str: 16, intel: 18 } },
  { name: 'Bristleback', main_attr: 'str', attrs: { agi: 23, str: 17, intel: 21 } },
  { name: 'Broodmother', main_attr: 'agi', attrs: { agi: 21, str: 19, intel: 22 } },
  { name: 'Centaur Warrunner', main_attr: 'str', attrs: { agi: 24, str: 20, intel: 22 } },
  { name: 'Chaos Knight', main_attr: 'str', attrs: { agi: 18, str: 18, intel: 17 } },
  { name: 'Chen', main_attr: 'intel', attrs: { agi: 19, str: 20, intel: 25 } },
  { name: 'Clinkz', main_attr: 'agi', attrs: { agi: 22, str: 22, intel: 25 } },
  { name: 'Clockwerk', main_attr: 'str', attrs: { agi: 21, str: 23, intel: 25 } },
  { name: 'Crystal Maiden', main_attr: 'intel', attrs: { agi: 21, str: 24, intel: 20 } },
  { name: 'Dark Seer', main_attr: 'intel', attrs: { agi: 21, str: 18, intel: 19 } },
  { name: 'Dark Willow', main_attr: 'intel', attrs: { agi: 22, str: 24, intel: 18 } },
  { name: 'Dawnbreaker', main_attr: 'str', attrs: { agi: 18, str: 15, intel: 15 } },
  { name: 'Dazzle', main_attr: 'intel', attrs: { agi: 25, str: 15, intel: 18 } },
  { name: 'Death Prophet', main_attr: 'intel', attrs: { agi: 22, str: 24, intel: 16 } },
  { name: 'Disruptor', main_attr: 'intel', attrs: { agi: 19, str: 20, intel: 23 } },
  { name: 'Doom', main_attr: 'str', attrs: { agi: 16, str: 16, intel: 24 } },
  { name: 'Dragon Knight', main_attr: 'str', attrs: { agi: 25, str: 19, intel: 20 } },
  { name: 'Drow Ranger', main_attr: 'agi', attrs: { agi: 22, str: 18, intel: 22 } },
  { name: 'Earth Spirit', main_attr: 'str', attrs: { agi: 18, str: 20, intel: 21 } },
  { name: 'Earthshaker', main_attr: 'str', attrs: { agi: 19, str: 16, intel: 22 } },
  { name: 'Elder Titan', main_attr: 'str', attrs: { agi: 23, str: 18, intel: 24 } },
  { name: 'Ember Spirit', main_attr: 'agi', attrs: { agi: 23, str: 21, intel: 20 } },
  { name: 'Enchantress', main_attr: 'intel', attrs: { agi: 19, str: 17, intel: 17 } },
  { name: 'Enigma', main_attr: 'intel', attrs: { agi: 24, str: 22, intel: 18 } },
  { name: 'Faceless Void', main_attr: 'agi', attrs: { agi: 15, str: 25, intel: 22 } },
  { name: 'Grimstroke', main_attr: 'intel', attrs: { agi: 21, str: 23, intel: 18 } },
  { name: 'Gyrocopter', main_attr: 'agi', attrs: { agi: 24, str: 20, intel: 20 } },
  { name: 'Hoodwink', main_attr: 'agi', attrs: { agi: 18, str: 21, intel: 24 } },
  { name: 'Huskar', main_attr: 'str', attrs: { agi: 21, str: 15, intel: 25 } },
  { name: 'Invoker', main_attr: 'intel', attrs: { agi: 22, str: 21, intel: 18 } },
  { name: 'Io', main_attr: 'intel', attrs: { agi: 24, str: 20, intel: 20 } },
  { name: 'Jakiro', main_attr: 'intel', attrs: { agi: 24, str: 22, intel: 15 } },
  { name: 'Juggernaut', main_attr: 'agi', attrs: { agi: 20, str: 22, intel: 22 } },
  { name: 'Keeper of the Light', main_attr: 'intel', attrs: { agi: 15, str: 24, intel: 24 } },
  { name: 'Kunkka', main_attr: 'str', attrs: { agi: 20, str: 24, intel: 16 } },
  { name: 'Legion Commander', main_attr: 'str', attrs: { agi: 16, str: 21, intel: 15 } },
  { name: 'Leshrac', main_attr: 'intel', attrs: { agi: 25, str: 23, intel: 23 } },
  { name: 'Lich', main_attr: 'intel', attrs: { agi: 19, str: 19, intel: 23 } },
  { name: 'Lifestealer', main_attr: 'str', attrs: { agi: 16, str: 23, intel: 24 } },
  { name: 'Lina', main_attr: 'intel', attrs: { agi: 20, str: 18, intel: 18 } },
  { name: 'Lion', main_attr: 'intel', attrs: { agi: 23, str: 21, intel: 18 } },
  { name: 'Lone Druid', main_attr: 'str', attrs: { agi: 22, str: 23, intel: 20 } },
  { name: 'Luna', main_attr: 'agi', attrs: { agi: 19, str: 22, intel: 24 } },
  { name: 'Lycan', main_attr: 'str', attrs: { agi: 25, str: 22, intel: 21 } },
  { name: 'Magnus', main_attr: 'str', attrs: { agi: 18, str: 20, intel: 22 } },
  { name: 'Marci', main_attr: 'str', attrs: { agi: 17, str: 23, intel: 18 } },
  { name: 'Mars', main_attr: 'str', attrs: { agi: 19, str: 18, intel: 17 } },
  { name: 'Medusa', main_attr: 'agi', attrs: { agi: 24, str: 22, intel: 16 } },
  { name: 'Meepo', main_attr: 'agi', attrs: { agi: 15, str: 21, intel: 24 } },
  { name: 'Mirana', main_attr: 'agi', attrs: { agi: 23, str: 22, intel: 19 } },
  { name: 'Monkey King', main_attr: 'agi', attrs: { agi: 21, str: 25, intel: 22 } },
  { name: 'Morphling', main_attr: 'agi', attrs: { agi: 20, str: 22, intel: 18 } },
  { name: 'Naga Siren', main_attr: 'agi', attrs: { agi: 19, str: 25, intel: 21 } },
  { name: "Nature's Prophet", main_attr: 'intel', attrs: { agi: 23, str: 19, intel: 20 } },
  { name: 'Necrophos', main_attr: 'intel', attrs: { agi: 18, str: 20, intel: 22 } },
  { name: 'Night Stalker', main_attr: 'str', attrs: { agi: 23, str: 19, intel: 18 } },
  { name: 'Nyx Assassin', main_attr: 'intel', attrs: { agi: 16, str: 22, intel: 24 } },
  { name: 'Ogre Magi', main_attr: 'str', attrs: { agi: 18, str: 20, intel: 21 } },
  { name: 'Omniknight', main_attr: 'str', attrs: { agi: 17, str: 23, intel: 20 } },
  { name: 'Oracle', main_attr: 'intel', attrs: { agi: 24, str: 21, intel: 18 } },
  { name: 'Outworld Destroyer', main_attr: 'intel', attrs: { agi: 19, str: 18, intel: 23 } },
  { name: 'Pangolier', main_attr: 'agi', attrs: { agi: 25, str: 24, intel: 22 } },
  { name: 'Phantom Assassin', main_attr: 'agi', attrs: { agi: 18, str: 23, intel: 16 } },
  { name: 'Phantom Lancer', main_attr: 'agi', attrs: { agi: 22, str: 19, intel: 17 } },
  { name: 'Phoenix', main_attr: 'str', attrs: { agi: 17, str: 25, intel: 24 } },
  { name: 'Primal Beast', main_attr: 'str', attrs: { agi: 19, str: 21, intel: 20 } },
  { name: 'Puck', main_attr: 'intel', attrs: { agi: 24, str: 20, intel: 21 } },
  { name: 'Pudge', main_attr: 'str', attrs: { agi: 15, str: 23, intel: 22 } },
  { name: 'Pugna', main_attr: 'intel', attrs: { agi: 20, str: 24, intel: 25 } },
  { name: 'Queen of Pain', main_attr: 'intel', attrs: { agi: 23, str: 19, intel: 20 } },
  { name: 'Razor', main_attr: 'agi', attrs: { agi: 24, str: 25, intel: 17 } },
  { name: 'Riki', main_attr: 'agi', attrs: { agi: 23, str: 18, intel: 22 } },
  { name: 'Rubick', main_attr: 'intel', attrs: { agi: 19, str: 21, intel: 25 } },
  { name: 'Sand King', main_attr: 'str', attrs: { agi: 16, str: 19, intel: 24 } },
  { name: 'Shadow Demon', main_attr: 'intel', attrs: { agi: 20, str: 21, intel: 22 } },
  { name: 'Shadow Fiend', main_attr: 'agi', attrs: { agi: 18, str: 23, intel: 21 } },
  { name: 'Shadow Shaman', main_attr: 'intel', attrs: { agi: 22, str: 24, intel: 19 } },
  { name: 'Silencer', main_attr: 'intel', attrs: { agi: 21, str: 19, intel: 25 } },
  { name: 'Skywrath Mage', main_attr: 'intel', attrs: { agi: 17, str: 18, intel: 23 } },
  { name: 'Slardar', main_attr: 'str', attrs: { agi: 18, str: 20, intel: 22 } },
  { name: 'Slark', main_attr: 'agi', attrs: { agi: 25, str: 17, intel: 22 } },
  { name: 'Snapfire', main_attr: 'agi', attrs: { agi: 16, str: 21, intel: 24 } },
  { name: 'Sniper', main_attr: 'agi', attrs: { agi: 20, str: 19, intel: 24 } },
  { name: 'Spectre', main_attr: 'agi', attrs: { agi: 24, str: 23, intel: 20 } },
  { name: 'Spirit Breaker', main_attr: 'str', attrs: { agi: 21, str: 25, intel: 16 } },
  { name: 'Storm Spirit', main_attr: 'intel', attrs: { agi: 15, str: 22, intel: 23 } },
  { name: 'Sven', main_attr: 'str', attrs: { agi: 22, str: 23, intel: 17 } },
  { name: 'Techies', main_attr: 'intel', attrs: { agi: 19, str: 24, intel: 18 } },
  { name: 'Templar Assassin', main_attr: 'agi', attrs: { agi: 21, str: 19, intel: 17 } },
  { name: 'Terrorblade', main_attr: 'agi', attrs: { agi: 23, str: 21, intel: 24 } },
  { name: 'Tidehunter', main_attr: 'str', attrs: { agi: 19, str: 25, intel: 17 } },
  { name: 'Timbersaw', main_attr: 'str', attrs: { agi: 22, str: 16, intel: 21 } },
  { name: 'Tinker', main_attr: 'intel', attrs: { agi: 21, str: 23, intel: 23 } },
  { name: 'Tiny', main_attr: 'str', attrs: { agi: 15, str: 19, intel: 16 } },
  { name: 'Treant Protector', main_attr: 'str', attrs: { agi: 18, str: 17, intel: 19 } },
  { name: 'Troll Warlord', main_attr: 'agi', attrs: { agi: 15, str: 16, intel: 17 } },
  { name: 'Tusk', main_attr: 'str', attrs: { agi: 21, str: 24, intel: 19 } },
  { name: 'Underlord', main_attr: 'str', attrs: { agi: 23, str: 19, intel: 25 } },
  { name: 'Undying', main_attr: 'str', attrs: { agi: 16, str: 24, intel: 23 } },
  { name: 'Ursa', main_attr: 'agi', attrs: { agi: 25, str: 24, intel: 19 } },
  { name: 'Vengeful Spirit', main_attr: 'agi', attrs: { agi: 24, str: 16, intel: 25 } },
  { name: 'Venomancer', main_attr: 'agi', attrs: { agi: 18, str: 21, intel: 16 } },
  { name: 'Viper', main_attr: 'agi', attrs: { agi: 22, str: 21, intel: 22 } },
  { name: 'Visage', main_attr: 'intel', attrs: { agi: 15, str: 20, intel: 15 } },
  { name: 'Void Spirit', main_attr: 'intel', attrs: { agi: 25, str: 17, intel: 16 } },
  { name: 'Warlock', main_attr: 'intel', attrs: { agi: 25, str: 18, intel: 15 } },
  { name: 'Weaver', main_attr: 'agi', attrs: { agi: 15, str: 19, intel: 24 } },
  { name: 'Windranger', main_attr: 'agi', attrs: { agi: 20, str: 25, intel: 15 } },
  { name: 'Winter Wyvern', main_attr: 'intel', attrs: { agi: 25, str: 21, intel: 23 } },
  { name: 'Witch Doctor', main_attr: 'intel', attrs: { agi: 16, str: 16, intel: 22 } },
  { name: 'Wraith King', main_attr: 'str', attrs: { agi: 24, str: 19, intel: 23 } },
  { name: 'Zeus', main_attr: 'intel', attrs: { agi: 20, str: 20, intel: 25 } },
];

heroes.forEach((hero) => {
  const heroNameLowercase = hero.name.toLowerCase().replace(/ /g, '_');
  hero.image_url = `https://cdn.dota2.com/apps/dota2/images/heroes/${heroNameLowercase}_vert.jpg`;
});

export default heroes;


// https://cdn.akamai.steamstatic.com/apps/dota2/videos/dota_react/heroes/renders/pudge.webm